function
RuslanNanai/doingsdone pull request #3
Opened 2022-07-08 14:41 UTC by RuslanNanai

2022-07-11 10:19 UTC, kuptsov-se requested changes
Все супер, задание выполнено правильно, поправь код стайл и пойдем дальше

2022-07-11 10:19 UTC, kuptsov-se commented on arrays.php
> +foreach ($students as $student){
код стайл, не хватает пробела

2022-07-11 10:19 UTC, kuptsov-se commented on arrays.php
> +    $avgMarksStudent = avgMarks($student['math'], $student['ukr'], $student['eng']);
отлично, молодчага, это то что надо было

2022-07-11 10:19 UTC, kuptsov-se commented on arrays.php
> +function avgMarks($mathMark, $ukrMark, $engMark){
тут все правильно, не хватает пробела по кодстайлу + вынесем на обсудить ещё раз типы данных + вопрос типизации аргументов и возвращаемых типов

2022-07-15 15:25 UTC, RuslanNanai commented on arrays.php
> +foreach ($students as $student){
++

2022-07-15 15:27 UTC, RuslanNanai commented on arrays.php
> +    $avgMarksStudent = avgMarks($student['math'], $student['ukr'], $student['eng']);
+

2022-07-15 15:27 UTC, RuslanNanai commented on arrays.php
> +function avgMarks($mathMark, $ukrMark, $engMark){
+

2022-07-16 08:07 UTC, kuptsov-se approved these changes

2022-07-16 08:07 UTC, merged